# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Vote Flux site v2
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Flux website refresh...
# baseurl: "/vote-flux-concept" # the subpath of your site, e.g. /blog
# baseurl: ""
baseurl: "/site-v2-concept"
url: "http://yourdomain.com" # the base hostname & protocol for your site
icon_path: /img/social-icons/

collections:
  about:
    output: true



# Build settings
markdown: kramdown
incremental: true
exclude:
  - node_modules
  - README.md
  - package.json
  - gulpfile.js
  - react-signup
  - docs
  - npm-debug.log
  - to-do
  - index-old.html


page_gen-dirs: true # uncomment, if you prefer to generate named folders
page_gen:
  - data: 'press'
    template: 'press'
    name: 'title'
    dir: 'press'
